### ISSUE TITLE
Git clone takes ages because of big files in the history

### ISSUE THREAD

**Issue by T-vK** [angela-d/firmware_oneplus#1]
If you do a git clone from scratch, it takes ages because it has to downlaod hundreds of MB of files that used to be in this repository (and still are because they are in the git history). It would be nice if you could either alter the git history removing those files or at least mention it in the README.

Personally I cancelled my git clone after a minute because it took too long. Then I used:

```
git clone --depth=1 https://github.com/angela-d/firmware_oneplus.git
```
so that it only downloads the files contained in the latest commit. You could mention that command in the README.

Other than that, I love it and it worked great for me.

One more question: Can you tell me what this `update-binary` file is and what this part of the original updater-script does?

``` 
ifelse(msm.boot_update("backup"), (
package_extract_file("firmware-update/cmnlib64.mbn", "/dev/block/bootdevice/by-name/cmnlib64bak");
package_extract_file("firmware-update/cmnlib.mbn", "/dev/block/bootdevice/by-name/cmnlibbak");
package_extract_file("firmware-update/hyp.mbn", "/dev/block/bootdevice/by-name/hypbak");
package_extract_file("firmware-update/tz.mbn", "/dev/block/bootdevice/by-name/tzbak");
package_extract_file("firmware-update/abl.elf", "/dev/block/bootdevice/by-name/ablbak");
package_extract_file("firmware-update/keymaster.mbn", "/dev/block/bootdevice/by-name/keymasterbak");
package_extract_file("firmware-update/xbl.elf", "/dev/block/bootdevice/by-name/xblbak");
package_extract_file("firmware-update/rpm.mbn", "/dev/block/bootdevice/by-name/rpmbak");
), "");
```

Are these optional or do they serve a special purpose?

**Comment by angela-d** [comment]
Thanks for the suggestion of `--depth=1`! I'm going to add that shortly.

`updater-script` should pull the modems/radios and firmware update binaries.  What each (cmnlib64.mbn,  cmnlib.mbn) specifically does, I couldn't tell you as my knowledge of the Android filesystem is limited.

This portion was taken from the OxygenOS .zip - this part is updating the system portion of Android, so removing them would either not update the device or potentially cause booting errors.  I run this script on my daily device, so I don't have a means to test removing them. :)

You can confirm such is not malicious as the `package_extract_file` function is triggering files originally copied from the .zip you specified from Oneplus (they don't actually exist anywhere in this repo).

Example:
```bash
# Extract ROM
echo "Extracting from the source image..."
unzip -q "$OXYGEN_PATH" firmware-update/* -d "tmp/"
unzip -jq "$OXYGEN_PATH" RADIO/* -d "tmp/firmware-update/"
```
- $OXYGEN_PATH is what you entered during the start of `./extract` being run
- `firmware-update/` is a directory pulled during the **unzip** command and destined for a  temporary folder `tmp/`

If you unzip your OxygenOS zip, you'll see `firmware-update` as one of the main folders, with all of these files.

If you'd like to see it in action, add `exit` before the end of the script/any cleanup, or comment out the `cleanup()` function and you'll be able to see these folders before they get erased.

With regards to update-binary: [this wiki should help](https://source.android.com/devices/tech/ota/nonab/inside_packages)
